<?php if ($pageCount) : ?>
    <div class="text-center">
        <ul class="pagination justify-content-center">
            <?php if (isset($previous)) : ?>
                <li class="page-item">
                    <?php $query['page'] = $first; ?>
                    <a class="page-link" href="<?= $this->url(null, [], ['query' => array_filter($query)], true) ?>">
                        <span class="fas fa-step-backward" aria-hidden="true"></span>
                    </a>
                </li>
                <li class="page-item">
                    <?php $query['page'] = $previous; ?>
                    <a class="page-link" href="<?= $this->url(null, [], ['query' => array_filter($query)], true) ?>">
                        <span class="fas fa-backward" aria-hidden="true"></span>
                    </a>
                </li>
            <?php else : ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#"><span class="fas fa-step-backward" aria-hidden="true"></span></a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="#"><span class="fas fa-backward" aria-hidden="true"></span></a>
                </li>
            <?php endif; ?>

            <?php foreach ($pagesInRange as $page) : ?>
                <?php if ($page != $current) : ?>
                    <li class="page-item">
                        <?php $query['page'] = $page; ?>
                        <a class="page-link" href="<?= $this->url(null, [], ['query' => array_filter($query)], true) ?>"><?= $page ?></a>
                    </li>
                <?php else : ?>
                    <li class="page-item active">
                        <a class="page-link" href="#"><?= $page ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if (isset($next)) : ?>
                <li class="page-item">
                    <?php $query['page'] = $next; ?>
                    <a class="page-link" href="<?= $this->url(null, [], ['query' => array_filter($query)], true) ?>">
                        <span class="fas fa-forward" aria-hidden="true"></span>
                    </a>
                </li>
                <li class="page-item">
                    <?php $query['page'] = $last; ?>
                    <a class="page-link" href="<?= $this->url(null, [], ['query' => array_filter($query)], true) ?>">
                        <span class="fas fa-step-forward" aria-hidden="true"></span>
                    </a>
                </li>
            <?php else : ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#"><span class="fas fa-forward" aria-hidden="true"></span></a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="#"><span class="fas fa-step-forward" aria-hidden="true"></span></a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>