<?php if ($pageCount): ?>
    <div class="text-center">
        <ul class="pagination">
            <?php if (isset($previous)): ?>
                <li>
                    <?php $query['page'] = $first; ?>
                    <a href="<?php echo $this->url(null, [], ['query' => array_filter($query)], true); ?>">
                        <span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span>
                    </a>
                </li>
                <li>
                    <?php $query['page'] = $previous; ?>
                    <a href="<?php echo $this->url(null, [], ['query' => array_filter($query)], true); ?>">
                        <span class="glyphicon glyphicon-backward" aria-hidden="true"></span>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#"><span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span></a>
                </li>
                <li class="disabled">
                    <a href="#"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></a>
                </li>
            <?php endif; ?>

            <?php foreach ($pagesInRange as $page): ?>
                <?php if ($page != $current): ?>
                    <li>
                        <?php $query['page'] = $page; ?>
                        <a href="<?php echo $this->url(null, [], ['query' => array_filter($query)], true); ?>"><?php echo $page; ?></a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if (isset($next)): ?>
                <li>
                    <?php $query['page'] = $next; ?>
                    <a href="<?php echo $this->url(null, [], ['query' => array_filter($query)], true); ?>">
                        <span class="glyphicon glyphicon-forward" aria-hidden="true"></span>
                    </a>
                </li>
                <li>
                    <?php $query['page'] = $last; ?>
                    <a href="<?php echo $this->url(null, [], ['query' => array_filter($query)], true); ?>">
                        <span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#"><span class="glyphicon glyphicon-forward" aria-hidden="true"></span></a>
                </li>
                <li class="disabled">
                    <a href="#"><span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span></a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>